apiVersion: v1
kind: Service
metadata:
  name: ConfStream-App
  namespace: confstream
spec:
  type: LoadBalancer
  selector:
    app: ConfStream-App
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000